version: "3.0"
services:
  web1:
    image: nginx 
    volumes:
    - ./srv1:/usr/share/nginx/html:ro

  web2:
    image: nginx 
    volumes:
    - ./srv2:/usr/share/nginx/html:ro


  slb:
    image: haproxy
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
    - 80:80
    depends_on:
    - web1
    - web2

